name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    # Only run for valid semver tags without 'v' prefix
    if: |
      contains(github.ref, 'refs/tags/') && 
      matches(github.ref, '^refs/tags/[0-9]+\\.[0-9]+\\.[0-9]+(-[a-zA-Z0-9\\.\\-]+)?(\\+[a-zA-Z0-9\\.\\-]+)?$')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci

      - run: npx tsc -noEmit -skipLibCheck

      - run: npx eslint . --ext .ts

      - run: npm run build

      - name: Package
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          zip "mono-task-note-${VERSION}.zip" main.js manifest.json styles.css 2>/dev/null || \
          zip "mono-task-note-${VERSION}.zip" main.js manifest.json

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          # Pre-release flag for hyphenated versions (e.g., 1.2.3-beta)
          PRERELEASE_FLAG=""
          if [[ "$VERSION" == *-* ]]; then PRERELEASE_FLAG="--prerelease"; fi

          ASSETS=(main.js manifest.json "mono-task-note-${VERSION}.zip")
          [[ -f styles.css ]] && ASSETS+=(styles.css)

          # Create release with auto-generated notes
          gh release create "$VERSION" \
            --title "$VERSION" \
            --generate-notes \
            $PRERELEASE_FLAG \
            "${ASSETS[@]}"
